image: maven:3.3.9

pipelines:
  tags:
    v*:
      - step:
          caches:
            - maven
          script:
            - mvn clean install
            - mv target/ItemEventSearch-*.jar target/ItemEventSearch-${BITBUCKET_TAG}.jar
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/ItemEventSearch-${BITBUCKET_TAG}.jar"